#server and amqp stanzas are mandatory for a SimpleAmqpServer
server:
  name: dspace_amqp_server
  sleep_on_empty: 5
amqp:
  #queues for communication to and from caller. As expected, receive on incoming_queue and send result on outgoing_queue
  incoming_queue: va_to_ideals
  outgoing_queue: ideals_to_va
  #Connection information, passed directly to Bunny.new, whose defaults are used for anything missing
  #Note that Bunny will want these as symbols, so the YAML should reflect that
  connection:
    :port: 5672